### ISSUE TITLE
Custom data imports to wrong tiles

### ISSUE THREAD

**Issue by BuyMyMojo** [heygleeson/godot-ldtk-importer#4] opened 2023-11-06 12:11 UTC
Importing custom data into Godot 4.2-beta4 has the data get offset by 1 on the X axis

Tiles with custom data in LDtk:
![image](https://github.com/heygleeson/godot-ldtk-importer/assets/46948241/0a1b710d-d54e-4ecb-b7df-e56a8fd7fb70)

Tiles with custom data after imported into Godot:
![image](https://github.com/heygleeson/godot-ldtk-importer/assets/46948241/8acf189a-0640-421e-be7b-1c4b2327fec2)

Project files:
[My Fishing Game.zip](https://github.com/heygleeson/godot-ldtk-importer/files/13266262/My.Fishing.Game.zip)

**Comment by heygleeson** [comment] 2023-11-07 12:07
Woops! I'll take a look at this when I get the chance. Expect a fix later this week/early next week.

**Comment by MarcinKuder** [comment] 2024-01-28 10:33
This is caused by incorrect grid_w calculation. After applying the solution suggested by dinolaser ( https://github.com/heygleeson/godot-ldtk-importer/issues/6), custom data is correctly assigned.

**Comment by heygleeson** [comment] 2024-09-11 13:27
Fixed in [1.3](https://github.com/heygleeson/godot-ldtk-importer/releases/tag/1.3)

**Closed by heygleeson** 2024-09-11 13:27 UTC
